### ISSUE TITLE
malloc assertion failure followed by coredump on Manjaro ARM 20.08 / Pinebook Pro

### ISSUE THREAD

**Issue by feoh** [nesbox/TIC-80#1173]
Hi all!

tic-80 builds like a champ, but when I try to run the built program, I see:

```
[feoh@voyager TIC-80]$ build/bin/tic80

 TIC-80 tiny computer 0.80.1311-dev Pro
 http://tic80.com (C) 2020
tic80: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

```

I ran it under valgrind and the program works albeit obviously slowed down. I attached the log of memory errors it found.

When I run it under gdb, here's the stack trace I get:

```
feoh@voyager build]$ gdb bin/tic80
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/tic80...
(gdb) run
Starting program: /home/feoh/src/packages/TIC-80/build/bin/tic80 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0xffffdc8e1ee0 (LWP 73293)]
[New Thread 0xffffdc854ee0 (LWP 73294)]

 TIC-80 tiny computer 0.80.1311-dev Pro
 http://tic80.com (C) 2020
tic80: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

Thread 1 "tic80" received signal SIGABRT, Aborted.
0x0000fffff675a6c8 in raise () from /usr/lib/libc.so.6
(gdb) 
(gdb) bt
#0  0x0000fffff675a6c8 in raise () at /usr/lib/libc.so.6
#1  0x0000fffff67471cc in abort () at /usr/lib/libc.so.6
#2  0x0000fffff679b5b4 in __malloc_assert () at /usr/lib/libc.so.6
#3  0x0000fffff679d440 in sysmalloc () at /usr/lib/libc.so.6
#4  0x0000fffff679ead4 in _int_malloc () at /usr/lib/libc.so.6
#5  0x0000fffff679faf4 in malloc () at /usr/lib/libc.so.6
#6  0x0000fffff5bc2c0c in glXGetProcAddress () at /usr/lib/libGLX.so.0
#7  0x0000aaaaaabfe8d8 in _glewInit_GL_ARB_copy_image ()
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/externals/glew/glew.c:4720
#8  0x0000aaaaaac25f70 in glewContextInit ()
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/externals/glew/glew.c:10712
#9  0x0000aaaaaac3437c in glewInit ()
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/externals/glew/glew.c:14616
#10 0x0000aaaaaabd97b4 in CreateTargetFromWindow
    (renderer=0xaaaaab1bf960, windowID=2, target=0xaaaaab1bf9f0)
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/renderer_GL_common.inl:1642
#11 0x0000aaaaaabd8dc0 in Init
    (renderer=0xaaaaab1bf960, renderer_request=..., w=1024, h=576, SDL_flags=2)
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/renderer_GL_common.inl:1348
#12 0x0000aaaaaab7a608 in GPU_InitRendererByID (renderer_request=..., w=1024, h=576, SDL_flags=2)
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/SDL_gpu.c:456
#13 0x0000aaaaaab7a408 in GPU_Init (w=1024, h=576, SDL_flags=2)
    at /home/feoh/src/packages/TIC-80/vendor/sdl-gpu/src/SDL_gpu.c:424
#14 0x0000aaaaaab3ff18 in initGPU () at /home/feoh/src/packages/TIC-80/src/system/sdlgpu.c:328
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x0000aaaaaab42378 in start
    (argc=1, argv=0xfffffffff638, folder=0xaaaaab096710 <appFolder.0> "/home/feoh/.local/share/com.nesbox.tic/TIC-80/") at /home/feoh/src/packages/TIC-80/src/system/sdlgpu.c:1508
#16 0x0000aaaaaab4253c in main (argc=1, argv=0xfffffffff638)
    at /home/feoh/src/packages/TIC-80/src/system/sdlgpu.c:1662
(gdb) 

```

I'd love to help debugging this if I can. Does anyone have any suggestions on where to start? I know C but am hardly an expert.

Thanks in advance!
[valgrind.log](https://github.com/nesbox/TIC-80/files/5212083/valgrind.log)

**Comment by nesbox** [comment]
Hi,
we have the same issue here #1044, as a workaround try to fix CMakeLists.txt like in the comment https://github.com/nesbox/TIC-80/issues/1044#issuecomment-687893653

**Comment by feoh** [comment]
> Hi,
> we have the same issue here #1044, as a workaround try to fix CMakeLists.txt like in the comment [#1044 (comment)](https://github.com/nesbox/TIC-80/issues/1044#issuecomment-687893653)

That worked perfectly! So excited to have tic-80 building and running like a champ on my Pinebook Pro. Thanks a bunch!

Should I try to bend my brain around understanding CMake to try to make a pull request with a diff for this or will this work-around be unnecessary in a future version? :+1: 

In any case feel free to close this as a dupe.

**Comment by nesbox** [comment]
SDL GPU disabled by default here #1044
